/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as AdminProtectedRouteImport } from './routes/admin._protected'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSetPasswordRouteImport } from './routes/admin.set-password'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas.$city'
import { Route as AdminProtectedIndexRouteImport } from './routes/admin._protected.index'
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin._protected.dashboard'
import { Route as AdminProtectedDuplicatesRouteImport } from './routes/admin._protected.duplicates'
import { Route as AdminProtectedEmailRequestsRouteImport } from './routes/admin._protected.email-requests'
import { Route as AdminProtectedMailActivityRouteImport } from './routes/admin._protected.mail-activity'
import { Route as AdminProtectedNotificationsRouteImport } from './routes/admin._protected.notifications'
import { Route as AdminProtectedQuotesRouteImport } from './routes/admin._protected.quotes'
import { Route as AdminProtectedReportsRouteImport } from './routes/admin._protected.reports'
import { Route as AdminProtectedSettingsRouteImport } from './routes/admin._protected.settings'
import { Route as ApiPublicAppointmentNotifyRouteImport } from './routes/api/public/appointment-notify'
import { Route as ApiPublicAppointmentReadinessCheckRouteImport } from './routes/api/public/appointment-readiness-check'
import { Route as ApiPublicCrmFollowupDigestRouteImport } from './routes/api/public/crm-followup-digest'
import { Route as ApiPublicResendInboundRouteImport } from './routes/api/public/resend-inbound'
import { Route as ApiPublicStripeInvoiceWebhookRouteImport } from './routes/api/public/stripe-invoice-webhook'
import { Route as AdminProtectedCrmIndexRouteImport } from './routes/admin._protected.crm.index'
import { Route as AdminProtectedCrmContactIdRouteImport } from './routes/admin._protected.crm.$contactId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetPasswordRoute = AdminSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AdminRoute,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/service-areas/$city',
  path: '/service-areas/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedIndexRoute = AdminProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedDuplicatesRoute =
  AdminProtectedDuplicatesRouteImport.update({
    id: '/duplicates',
    path: '/duplicates',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedEmailRequestsRoute =
  AdminProtectedEmailRequestsRouteImport.update({
    id: '/email-requests',
    path: '/email-requests',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedMailActivityRoute =
  AdminProtectedMailActivityRouteImport.update({
    id: '/mail-activity',
    path: '/mail-activity',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedNotificationsRoute =
  AdminProtectedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedQuotesRoute = AdminProtectedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedReportsRoute = AdminProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedSettingsRoute = AdminProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const ApiPublicAppointmentNotifyRoute =
  ApiPublicAppointmentNotifyRouteImport.update({
    id: '/api/public/appointment-notify',
    path: '/api/public/appointment-notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAppointmentReadinessCheckRoute =
  ApiPublicAppointmentReadinessCheckRouteImport.update({
    id: '/api/public/appointment-readiness-check',
    path: '/api/public/appointment-readiness-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCrmFollowupDigestRoute =
  ApiPublicCrmFollowupDigestRouteImport.update({
    id: '/api/public/crm-followup-digest',
    path: '/api/public/crm-followup-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResendInboundRoute = ApiPublicResendInboundRouteImport.update({
  id: '/api/public/resend-inbound',
  path: '/api/public/resend-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeInvoiceWebhookRoute =
  ApiPublicStripeInvoiceWebhookRouteImport.update({
    id: '/api/public/stripe-invoice-webhook',
    path: '/api/public/stripe-invoice-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProtectedCrmIndexRoute = AdminProtectedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedCrmContactIdRoute =
  AdminProtectedCrmContactIdRouteImport.update({
    id: '/crm/$contactId',
    path: '/crm/$contactId',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/duplicates': typeof AdminProtectedDuplicatesRoute
  '/admin/email-requests': typeof AdminProtectedEmailRequestsRoute
  '/admin/mail-activity': typeof AdminProtectedMailActivityRoute
  '/admin/notifications': typeof AdminProtectedNotificationsRoute
  '/admin/quotes': typeof AdminProtectedQuotesRoute
  '/admin/reports': typeof AdminProtectedReportsRoute
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/api/public/appointment-notify': typeof ApiPublicAppointmentNotifyRoute
  '/api/public/appointment-readiness-check': typeof ApiPublicAppointmentReadinessCheckRoute
  '/api/public/crm-followup-digest': typeof ApiPublicCrmFollowupDigestRoute
  '/api/public/resend-inbound': typeof ApiPublicResendInboundRoute
  '/api/public/stripe-invoice-webhook': typeof ApiPublicStripeInvoiceWebhookRoute
  '/admin/': typeof AdminProtectedIndexRoute
  '/admin/crm/$contactId': typeof AdminProtectedCrmContactIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/crm/': typeof AdminProtectedCrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminProtectedIndexRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/duplicates': typeof AdminProtectedDuplicatesRoute
  '/admin/email-requests': typeof AdminProtectedEmailRequestsRoute
  '/admin/mail-activity': typeof AdminProtectedMailActivityRoute
  '/admin/notifications': typeof AdminProtectedNotificationsRoute
  '/admin/quotes': typeof AdminProtectedQuotesRoute
  '/admin/reports': typeof AdminProtectedReportsRoute
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/api/public/appointment-notify': typeof ApiPublicAppointmentNotifyRoute
  '/api/public/appointment-readiness-check': typeof ApiPublicAppointmentReadinessCheckRoute
  '/api/public/crm-followup-digest': typeof ApiPublicCrmFollowupDigestRoute
  '/api/public/resend-inbound': typeof ApiPublicResendInboundRoute
  '/api/public/stripe-invoice-webhook': typeof ApiPublicStripeInvoiceWebhookRoute
  '/admin/crm/$contactId': typeof AdminProtectedCrmContactIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/crm': typeof AdminProtectedCrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/set-password': typeof AdminSetPasswordRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/_protected/duplicates': typeof AdminProtectedDuplicatesRoute
  '/admin/_protected/email-requests': typeof AdminProtectedEmailRequestsRoute
  '/admin/_protected/mail-activity': typeof AdminProtectedMailActivityRoute
  '/admin/_protected/notifications': typeof AdminProtectedNotificationsRoute
  '/admin/_protected/quotes': typeof AdminProtectedQuotesRoute
  '/admin/_protected/reports': typeof AdminProtectedReportsRoute
  '/admin/_protected/settings': typeof AdminProtectedSettingsRoute
  '/api/public/appointment-notify': typeof ApiPublicAppointmentNotifyRoute
  '/api/public/appointment-readiness-check': typeof ApiPublicAppointmentReadinessCheckRoute
  '/api/public/crm-followup-digest': typeof ApiPublicCrmFollowupDigestRoute
  '/api/public/resend-inbound': typeof ApiPublicResendInboundRoute
  '/api/public/stripe-invoice-webhook': typeof ApiPublicStripeInvoiceWebhookRoute
  '/admin/_protected/': typeof AdminProtectedIndexRoute
  '/admin/_protected/crm/$contactId': typeof AdminProtectedCrmContactIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/_protected/crm/': typeof AdminProtectedCrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/book'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin/login'
    | '/admin/set-password'
    | '/service-areas/$city'
    | '/service-areas/'
    | '/admin/dashboard'
    | '/admin/duplicates'
    | '/admin/email-requests'
    | '/admin/mail-activity'
    | '/admin/notifications'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/settings'
    | '/api/public/appointment-notify'
    | '/api/public/appointment-readiness-check'
    | '/api/public/crm-followup-digest'
    | '/api/public/resend-inbound'
    | '/api/public/stripe-invoice-webhook'
    | '/admin/'
    | '/admin/crm/$contactId'
    | '/lovable/email/queue/process'
    | '/admin/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/book'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin/login'
    | '/admin/set-password'
    | '/service-areas/$city'
    | '/service-areas'
    | '/admin/dashboard'
    | '/admin/duplicates'
    | '/admin/email-requests'
    | '/admin/mail-activity'
    | '/admin/notifications'
    | '/admin/quotes'
    | '/admin/reports'
    | '/admin/settings'
    | '/api/public/appointment-notify'
    | '/api/public/appointment-readiness-check'
    | '/api/public/crm-followup-digest'
    | '/api/public/resend-inbound'
    | '/api/public/stripe-invoice-webhook'
    | '/admin/crm/$contactId'
    | '/lovable/email/queue/process'
    | '/admin/crm'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/book'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy-policy'
    | '/reviews'
    | '/services'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/admin/_protected'
    | '/admin/login'
    | '/admin/set-password'
    | '/service-areas/$city'
    | '/service-areas/'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/duplicates'
    | '/admin/_protected/email-requests'
    | '/admin/_protected/mail-activity'
    | '/admin/_protected/notifications'
    | '/admin/_protected/quotes'
    | '/admin/_protected/reports'
    | '/admin/_protected/settings'
    | '/api/public/appointment-notify'
    | '/api/public/appointment-readiness-check'
    | '/api/public/crm-followup-digest'
    | '/api/public/resend-inbound'
    | '/api/public/stripe-invoice-webhook'
    | '/admin/_protected/'
    | '/admin/_protected/crm/$contactId'
    | '/lovable/email/queue/process'
    | '/admin/_protected/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  ApiPublicAppointmentNotifyRoute: typeof ApiPublicAppointmentNotifyRoute
  ApiPublicAppointmentReadinessCheckRoute: typeof ApiPublicAppointmentReadinessCheckRoute
  ApiPublicCrmFollowupDigestRoute: typeof ApiPublicCrmFollowupDigestRoute
  ApiPublicResendInboundRoute: typeof ApiPublicResendInboundRoute
  ApiPublicStripeInvoiceWebhookRoute: typeof ApiPublicStripeInvoiceWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/set-password': {
      id: '/admin/set-password'
      path: '/set-password'
      fullPath: '/admin/set-password'
      preLoaderRoute: typeof AdminSetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/service-areas/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/duplicates': {
      id: '/admin/_protected/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AdminProtectedDuplicatesRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/email-requests': {
      id: '/admin/_protected/email-requests'
      path: '/email-requests'
      fullPath: '/admin/email-requests'
      preLoaderRoute: typeof AdminProtectedEmailRequestsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/mail-activity': {
      id: '/admin/_protected/mail-activity'
      path: '/mail-activity'
      fullPath: '/admin/mail-activity'
      preLoaderRoute: typeof AdminProtectedMailActivityRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/notifications': {
      id: '/admin/_protected/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminProtectedNotificationsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/quotes': {
      id: '/admin/_protected/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminProtectedQuotesRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/reports': {
      id: '/admin/_protected/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminProtectedReportsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/settings': {
      id: '/admin/_protected/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminProtectedSettingsRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/api/public/appointment-notify': {
      id: '/api/public/appointment-notify'
      path: '/api/public/appointment-notify'
      fullPath: '/api/public/appointment-notify'
      preLoaderRoute: typeof ApiPublicAppointmentNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/appointment-readiness-check': {
      id: '/api/public/appointment-readiness-check'
      path: '/api/public/appointment-readiness-check'
      fullPath: '/api/public/appointment-readiness-check'
      preLoaderRoute: typeof ApiPublicAppointmentReadinessCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm-followup-digest': {
      id: '/api/public/crm-followup-digest'
      path: '/api/public/crm-followup-digest'
      fullPath: '/api/public/crm-followup-digest'
      preLoaderRoute: typeof ApiPublicCrmFollowupDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-inbound': {
      id: '/api/public/resend-inbound'
      path: '/api/public/resend-inbound'
      fullPath: '/api/public/resend-inbound'
      preLoaderRoute: typeof ApiPublicResendInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-invoice-webhook': {
      id: '/api/public/stripe-invoice-webhook'
      path: '/api/public/stripe-invoice-webhook'
      fullPath: '/api/public/stripe-invoice-webhook'
      preLoaderRoute: typeof ApiPublicStripeInvoiceWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/crm/': {
      id: '/admin/_protected/crm/'
      path: '/crm'
      fullPath: '/admin/crm/'
      preLoaderRoute: typeof AdminProtectedCrmIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/crm/$contactId': {
      id: '/admin/_protected/crm/$contactId'
      path: '/crm/$contactId'
      fullPath: '/admin/crm/$contactId'
      preLoaderRoute: typeof AdminProtectedCrmContactIdRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute
  AdminProtectedDuplicatesRoute: typeof AdminProtectedDuplicatesRoute
  AdminProtectedEmailRequestsRoute: typeof AdminProtectedEmailRequestsRoute
  AdminProtectedMailActivityRoute: typeof AdminProtectedMailActivityRoute
  AdminProtectedNotificationsRoute: typeof AdminProtectedNotificationsRoute
  AdminProtectedQuotesRoute: typeof AdminProtectedQuotesRoute
  AdminProtectedReportsRoute: typeof AdminProtectedReportsRoute
  AdminProtectedSettingsRoute: typeof AdminProtectedSettingsRoute
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
  AdminProtectedCrmContactIdRoute: typeof AdminProtectedCrmContactIdRoute
  AdminProtectedCrmIndexRoute: typeof AdminProtectedCrmIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedDuplicatesRoute: AdminProtectedDuplicatesRoute,
  AdminProtectedEmailRequestsRoute: AdminProtectedEmailRequestsRoute,
  AdminProtectedMailActivityRoute: AdminProtectedMailActivityRoute,
  AdminProtectedNotificationsRoute: AdminProtectedNotificationsRoute,
  AdminProtectedQuotesRoute: AdminProtectedQuotesRoute,
  AdminProtectedReportsRoute: AdminProtectedReportsRoute,
  AdminProtectedSettingsRoute: AdminProtectedSettingsRoute,
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
  AdminProtectedCrmContactIdRoute: AdminProtectedCrmContactIdRoute,
  AdminProtectedCrmIndexRoute: AdminProtectedCrmIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

interface AdminRouteChildren {
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSetPasswordRoute: typeof AdminSetPasswordRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminSetPasswordRoute: AdminSetPasswordRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  ApiPublicAppointmentNotifyRoute: ApiPublicAppointmentNotifyRoute,
  ApiPublicAppointmentReadinessCheckRoute:
    ApiPublicAppointmentReadinessCheckRoute,
  ApiPublicCrmFollowupDigestRoute: ApiPublicCrmFollowupDigestRoute,
  ApiPublicResendInboundRoute: ApiPublicResendInboundRoute,
  ApiPublicStripeInvoiceWebhookRoute: ApiPublicStripeInvoiceWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
